name: Discord Webhook
on: [push]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Run Discord Webhook
      uses: Mist3r-Robot/discord-webhook@master
      with:
        id: ${{ secrets.752213009975214221 }}
        token: ${{ secrets.V95e2AtRTpOxzkc0GvxeCewrLwXq2PylhaPnEgi-fI8nQRcvq5If4g0iAtArQEdv5RYv
